/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author Dhany
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        mFrmkategori = new javax.swing.JMenuItem();
        mFrmAnggota = new javax.swing.JMenuItem();
        mFrmBuku = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        tFrmPeminjaman = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMaster.setText("Master");

        mFrmkategori.setText("Form Kategori");
        mFrmkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmkategoriActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmkategori);

        mFrmAnggota.setText("Form Anggota");
        mFrmAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmAnggotaActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmAnggota);

        mFrmBuku.setText("Form Buku");
        mFrmBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmBukuActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmBuku);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        tFrmPeminjaman.setText("Form Peminjaman");
        tFrmPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFrmPeminjamanActionPerformed(evt);
            }
        });
        menuTransaksi.add(tFrmPeminjaman);

        jMenuBar1.add(menuTransaksi);

        jMenu3.setText("Log Out");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFrmkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmkategoriActionPerformed
        // TODO add your handling code here:
        FrmKategori formKategori = new FrmKategori();
        formKategori.setVisible(true);
    }//GEN-LAST:event_mFrmkategoriActionPerformed

    private void mFrmAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmAnggotaActionPerformed
        // TODO add your handling code here:
        FrmAnggota formAnggota = new FrmAnggota();
        formAnggota.setVisible(true);
        
    }//GEN-LAST:event_mFrmAnggotaActionPerformed

    private void mFrmBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmBukuActionPerformed
        // TODO add your handling code here:
        FrmBuku formBuku = new FrmBuku();
        formBuku.setVisible(true);
    }//GEN-LAST:event_mFrmBukuActionPerformed

    private void tFrmPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFrmPeminjamanActionPerformed
        // TODO add your handling code here:
        FrmPeminjaman formPeminjaman = new FrmPeminjaman();
        formPeminjaman.setVisible(true);
    }//GEN-LAST:event_tFrmPeminjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mFrmAnggota;
    private javax.swing.JMenuItem mFrmBuku;
    private javax.swing.JMenuItem mFrmkategori;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem tFrmPeminjaman;
    // End of variables declaration//GEN-END:variables
}
